(()=>{
'use strict';
const API='https://oeacgchzyilgqzaqxssh.supabase.co/functions/v1/ypt-feedback';
const DEFAULT={url:'https://oeacgchzyilgqzaqxssh.supabase.co',key:'sb_publishable_boL9uWFxb1hcOx7o9nb9Rw_OERUARlv'};
const $=s=>document.querySelector(s);let db=null;
function config(){try{return JSON.parse(localStorage.getItem('rh_ypt_supabase'))||DEFAULT}catch{return DEFAULT}}
function client(){if(db)return db;const c=config();db=window.supabase?.createClient(c.url||DEFAULT.url,c.key||DEFAULT.key);return db}
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function schema(average,total){let el=$('#ratingStructuredData');if(!el){el=document.createElement('script');el.id='ratingStructuredData';el.type='application/ld+json';document.head.appendChild(el)}const data={'@context':'https://schema.org','@type':'SoftwareApplication',name:'YPT by Rathod — RATHOD HUB 2.0',url:'https://teachnlogy7509-pixel.github.io/RATHOD-HUB-2.0/',applicationCategory:'EducationalApplication',operatingSystem:'Web, Android',offers:{'@type':'Offer',price:'0',priceCurrency:'INR'}};if(total)data.aggregateRating={'@type':'AggregateRating',ratingValue:String(average),ratingCount:String(total),bestRating:'5',worstRating:'1'};el.textContent=JSON.stringify(data)}
function render(d){const rows=d.reviews||[],avg=Number(d.average||0),total=Number(d.total||0);$('#feedbackAverage').textContent=total?avg.toFixed(1):'—';$('#feedbackTotal').textContent=total?`${total} public rating${total===1?'':'s'}`:'No ratings yet';$('#feedbackList').innerHTML=rows.length?rows.slice(0,6).map(x=>`<article class="feedback-item"><header><b>${esc(x.name)}</b><span>${'★'.repeat(x.rating)}${'☆'.repeat(5-x.rating)}</span></header><p>${esc(x.message)}</p></article>`).join(''):'<article class="feedback-item"><p>पहली rating आपकी हो सकती है 😊</p></article>';schema(avg,total)}
async function load(){try{const r=await fetch(API,{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error();render(d)}catch{$('#feedbackList').innerHTML='<article class="feedback-item"><p>Ratings अभी load नहीं हो पाईं।</p></article>'}}
async function submit(e){e.preventDefault();const status=$('#feedbackStatus'),rating=Number(new FormData(e.target).get('rating')),message=$('#feedbackMessage').value.trim(),c=client();status.textContent='Saving…';const {data:{session}}=await c.auth.getSession();if(!session){status.textContent='Rating देने के लिए पहले Login करें।';$('#authDialog')?.showModal();return}const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({rating,message})}),d=await r.json().catch(()=>({}));if(!r.ok){status.textContent=d.error||'Rating save नहीं हुई।';return}status.textContent='धन्यवाद! आपकी public rating save हो गई ✅';e.target.reset();render(d)}
function boot(){$('[data-feedback-scroll]')?.addEventListener('click',()=>$('#feedbackPanel')?.scrollIntoView({behavior:'smooth',block:'start'}));$('#feedbackForm')?.addEventListener('submit',submit);load()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
