(()=>{
'use strict';
const ENDPOINT='https://rathod-ai-api.rathod-hub-ai.workers.dev/chat';
const HEALTH='https://rathod-ai-api.rathod-hub-ai.workers.dev/';
const IMAGE_ENDPOINT='https://rathod-ai-api.rathod-hub-ai.workers.dev/image';
const SUPABASE_DEFAULT={url:'https://oeacgchzyilgqzaqxssh.supabase.co',key:'sb_publishable_boL9uWFxb1hcOx7o9nb9Rw_OERUARlv'};
let imageClient=null;
const KEY='rh2_rathod_ai_history_v1';
const $=s=>document.querySelector(s);
let sending=false,history=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function load(){try{history=JSON.parse(localStorage.getItem(KEY)||'[]');if(!Array.isArray(history))history=[]}catch{history=[]}if(!history.length)history=[{role:'assistant',content:'नमस्ते! मैं Rathod AI हूँ 😊\nNEET, study planning, याद करने की tricks, motivation या RATHOD HUB 2.0—जो पूछना है पूछिए।',time:Date.now(),welcome:true}];render()}
function save(){try{localStorage.setItem(KEY,JSON.stringify(history.slice(-500)))}catch{history=history.slice(-150);localStorage.setItem(KEY,JSON.stringify(history))}}
function render(){const root=$('#rathodAiMessages');if(!root)return;root.innerHTML=history.map((m,i)=>`<article class="rh-ai-message ${m.role}"><div class="rh-ai-avatar">${m.role==='assistant'?'R':'●'}</div><div><small>${m.role==='assistant'?'RATHOD AI':'YOU'}</small><p>${esc(m.content).replace(/\n/g,'<br>')}</p>${m.provider?`<em>${esc(m.provider)}</em>`:''}</div></article>`).join('');root.scrollTop=root.scrollHeight;$('#rathodAiMemoryCount').textContent=`${history.filter(x=>!x.welcome).length} messages remembered`}
function add(role,content,extra={}){history.push({role,content,time:Date.now(),...extra});save();render()}
function setBusy(on){sending=on;const b=$('#rathodAiSend'),input=$('#rathodAiInput');if(b){b.disabled=on;b.innerHTML=on?'<i></i> सोच रहा हूँ…':'भेजें ➤'}if(input)input.disabled=on;$('#rathodAiTyping')?.classList.toggle('hidden',!on)}
async function send(text){text=String(text||'').trim();if(!text||sending)return;add('user',text);$('#rathodAiInput').value='';setBusy(true);try{if(!navigator.onLine)throw new Error('Internet बंद है। Chat history सुरक्षित है; online होते ही फिर भेजें।');const messages=history.filter(x=>!x.welcome).map(x=>({role:x.role,content:x.content}));const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`Rathod AI error (${r.status})`);add('assistant',String(data.text||'जवाब नहीं मिला। फिर कोशिश करें।').replace(/\*+/g,''),{provider:`${data.provider||'Rathod AI'} · ${data.model||'auto'}`})}catch(e){add('assistant',e.message||'अभी connection नहीं हो पाया। थोड़ी देर बाद फिर कोशिश करें।',{error:true})}finally{setBusy(false);$('#rathodAiInput')?.focus()}}
async function health(){try{const r=await fetch(HEALTH,{cache:'no-store'}),d=await r.json();const badge=$('#rathodAiStatus');if(!badge)return;if(d.configured){badge.textContent=`● ONLINE · ${d.configured}/7 AI`;badge.classList.add('online')}else{badge.textContent='○ API keys pending';badge.classList.remove('online')}}catch{$('#rathodAiStatus').textContent='○ Gateway offline'}}

function supabaseClient(){if(imageClient)return imageClient;let c=SUPABASE_DEFAULT;try{c=JSON.parse(localStorage.getItem('rh_ypt_supabase'))||SUPABASE_DEFAULT}catch{}imageClient=window.supabase?.createClient(c.url||SUPABASE_DEFAULT.url,c.key||SUPABASE_DEFAULT.key);return imageClient}
async function refreshImageLimit(){const label=$('#rathodImageLimit'),c=supabaseClient();if(!label||!c)return;const {data:{session}}=await c.auth.getSession();if(!session){label.textContent='Login · 3/day';return}const india=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());const {data}=await c.from('ypt_ai_image_usage').select('image_count').eq('user_id',session.user.id).eq('usage_date',india).maybeSingle();label.textContent=`${Math.max(0,3-Number(data?.image_count||0))} left today`}
async function generateImage(e){e.preventDefault();const c=supabaseClient(),status=$('#rathodImageStatus'),button=$('#rathodImageGenerate'),prompt=$('#rathodImagePrompt').value.trim();if(!prompt||!c)return;const {data:{session}}=await c.auth.getSession();if(!session){status.textContent='Image बनाने के लिए पहले Login करें।';$('#authDialog')?.showModal();return}button.disabled=true;status.textContent='🎨 Image बन रही है…';$('#rathodImageResult')?.classList.add('hidden');try{const r=await fetch(IMAGE_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${session.access_token}`},body:JSON.stringify({prompt})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Image error (${r.status})`);const src=`data:${d.mimeType||'image/png'};base64,${d.image}`;$('#rathodImagePreview').src=src;$('#rathodImageDownload').href=src;$('#rathodImageResult').classList.remove('hidden');$('#rathodImageLimit').textContent=`${Number(d.remaining||0)} left today`;status.textContent=`✅ ${d.provider||'AI'} image तैयार है`}catch(err){status.textContent=err.message||'Image नहीं बन पाई। फिर कोशिश करें।';await refreshImageLimit()}finally{button.disabled=false}}
function boot(){load();health();$('#rathodAiForm')?.addEventListener('submit',e=>{e.preventDefault();send($('#rathodAiInput').value)});document.querySelectorAll('[data-ai-prompt]').forEach(b=>b.onclick=()=>send(b.dataset.aiPrompt));$('#rathodAiNew')?.addEventListener('click',()=>{if(!confirm('Rathod AI की इस device वाली chat history साफ करें?'))return;history=[];localStorage.removeItem(KEY);load()});$('#rathodAiInput')?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#rathodAiForm').requestSubmit()}});window.addEventListener('online',health);$('#rathodImageForm')?.addEventListener('submit',generateImage);refreshImageLimit()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
