const VIP_SB={url:'https://oeacgchzyilgqzaqxssh.supabase.co',key:'sb_publishable_boL9uWFxb1hcOx7o9nb9Rw_OERUARlv'};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const local={get(k,d){try{return JSON.parse(localStorage.getItem('rh_vip_'+k))??d}catch{return d}},set(k,v){localStorage.setItem('rh_vip_'+k,JSON.stringify(v))}};
const dateKey=()=>new Date().toISOString().slice(0,10);const timeText=sec=>{sec=Math.max(0,Math.floor(sec||0));const h=Math.floor(sec/3600),m=Math.floor(sec%3600/60);return h?`${h}h ${m}m`:`${m}m`};
function avatarReference(value){const v=String(value||'').trim();if(!v)return '';if(/^rathod-avatar:[a-z0-9-]+$/i.test(v)||/^data:image\/webp;base64,[A-Za-z0-9+/]+={0,2}$/.test(v))return v;try{const u=new URL(v,location.href);return u.protocol==='https:'?u.href:''}catch{return ''}}
function avatarImage(value){const ref=avatarReference(value);if(ref.startsWith('rathod-avatar:')){const src=window.__rathodAvatarImage?.(ref.slice(14))||'';return /^data:image\/webp;base64,[A-Za-z0-9+/]+={0,2}$/.test(src)?src:''}return ref}
function equippedAvatar(){try{const a=JSON.parse(localStorage.getItem('rh_ypt_equippedAvatar')||'null');return a&&typeof a.src==='string'&&/^data:image\/webp;base64,[A-Za-z0-9+/]+={0,2}$/.test(a.src)?a:null}catch{return null}}
function studyverseAvatar(x){const name=x.display_name||'?';const src=avatarImage(x.avatar_url)||(user?.id&&x.user_id===user.id?avatarImage(userAvatarUrl)||equippedAvatar()?.src:'');const initials=esc(name.split(/\s+/).map(v=>v[0]).join('').slice(0,2));return `<span class="avatar${src?' has-reward-avatar':''}">${src?`<img class="profile-anime-avatar" src="${esc(src)}" alt="${esc(name)}">`:initials}</span>`}
function voiceAvatar(x){const src=avatarImage(x.avatar_url)||(user?.id&&x.id===user.id?avatarImage(userAvatarUrl)||equippedAvatar()?.src:'');return src?`<span class="avatar has-reward-avatar"><img class="profile-anime-avatar" src="${esc(src)}" alt="${esc(x.name||userName)}"></span>`:`<span>${x.muted?'🔇':'🎙️'}</span>`}

let client,user=null,userName='VIP Member',userAvatarUrl='',vip=false,pwSessions=local.get('pwSessions',[]),pwActive=local.get('pwActive',null),diaries=local.get('diaries',{}),notes=local.get('notes',[]),voice={channel:null,stream:null,peers:new Map(),pending:new Map(),muted:false,room:''};
function toast(m){const el=$('#toast');if(!el)return;el.textContent=m;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2800)}
async function session(){const {data}=await client.auth.getSession();user=data.session?.user||null;userName=user?.user_metadata?.full_name||user?.email?.split('@')[0]||'VIP Member';if(user){const {data:m}=await client.from('ypt_memberships').select('plan,active,expires_at').eq('user_id',user.id).maybeSingle();vip=Boolean(m?.active&&m.plan==='vip'&&(!m.expires_at||new Date(m.expires_at)>new Date()))||user.id==='07518017-1cfe-4b8e-b50f-807368123d4c';const {data:p}=await client.from('ypt_profiles').select('avatar_url').eq('id',user.id).maybeSingle();userAvatarUrl=avatarReference(p?.avatar_url)}else{vip=false;userAvatarUrl=''}}
function requireVip(){if(!user){$('#authDialog')?.showModal();return false}if(!vip){document.querySelector('[data-view="premium"]')?.click();toast('VIP coupon required');return false}return true}
function renderPw(){const d=$('#pwHistoryDate')?.value||dateKey();if($('#pwHistoryDate'))$('#pwHistoryDate').value=d;const rows=pwSessions.filter(x=>x.date===d).sort((a,b)=>new Date(b.started_at)-new Date(a.started_at));$('#pwHistory').innerHTML=rows.length?rows.map(x=>`<div class="history-entry pw-entry"><span>${x.complete?'✓':'◷'}</span><div><b>${esc(x.subject)} · ${esc(x.lecture)}</b><small>${x.progress}% · ${x.questions||0} attempted · ${x.wrong||0} wrong</small></div><time>${timeText(x.seconds)}</time></div>`).join(''):'<div class="empty-real"><b>No PW classes saved</b>इस तारीख की पहली class track करें।</div>';if(pwActive){const sec=Math.floor((Date.now()-pwActive.started)/1000);$('#pwStartFinish').textContent='■ Finish & save class';$('#pwActiveStatus').textContent=`${pwActive.subject} · ${pwActive.lecture} · ${timeText(sec)} running`;$('#pwSubject').value=pwActive.subject;$('#pwLecture').value=pwActive.lecture}else{$('#pwStartFinish').textContent='▶ Start PW Class';$('#pwActiveStatus').textContent=''}}
async function savePwCloud(row){if(!user)return;await client.from('ypt_pw_classes').upsert({id:row.id,user_id:user.id,class_date:row.date,subject:row.subject,lecture_name:row.lecture,duration_seconds:row.seconds,progress_percent:row.progress,questions_attempted:row.questions,wrong_answers:row.wrong,completed:row.complete,started_at:row.started_at,ended_at:row.ended_at})}
async function handlePw(e){e.preventDefault();if(!requireVip())return;if(!pwActive){pwActive={subject:$('#pwSubject').value,lecture:$('#pwLecture').value.trim(),started:Date.now()};local.set('pwActive',pwActive);try{if(window.AndroidFocus)AndroidFocus.openPwApp();else window.open('https://www.pw.live/','_blank','noopener')}catch{window.open('https://www.pw.live/','_blank','noopener')}renderPw();return}const row={id:crypto.randomUUID(),date:dateKey(),subject:pwActive.subject,lecture:pwActive.lecture,started_at:new Date(pwActive.started).toISOString(),ended_at:new Date().toISOString(),seconds:Math.max(1,Math.floor((Date.now()-pwActive.started)/1000)),progress:Number($('#pwProgress').value||0),questions:Number($('#pwQuestions').value||0),wrong:Number($('#pwWrong').value||0),complete:$('#pwComplete').checked};pwSessions.push(row);local.set('pwSessions',pwSessions);pwActive=null;local.set('pwActive',null);await savePwCloud(row);renderPw();toast('PW class saved')}
function diaryFor(d){return diaries[d]||{mood:'🔥 Motivated',entry:'',tomorrow:'',classDone:false,revisionDone:false,targetDone:false}}
function loadDiary(){const d=$('#diaryDate').value||dateKey();$('#diaryDate').value=d;const x=diaryFor(d);$('#diaryMood').value=x.mood;$('#diaryEntry').value=x.entry;$('#diaryTomorrow').value=x.tomorrow;$('#diaryClassDone').checked=x.classDone;$('#diaryRevisionDone').checked=x.revisionDone;$('#diaryTargetDone').checked=x.targetDone;$('#diarySaved').innerHTML=x.entry||x.tomorrow?`<div class="saved-diary-card"><b>${esc(x.mood)} · ${d}</b><p>${esc(x.entry||'No diary text')}</p><h4>Tomorrow</h4><p>${esc(x.tomorrow||'No plan')}</p><div><span class="${x.classDone?'done':''}">Class</span><span class="${x.revisionDone?'done':''}">Revision</span><span class="${x.targetDone?'done':''}">Target</span></div></div>`:'<div class="empty-real"><b>No entry for this date</b>अपना private diary note लिखें।</div>'}
async function saveDiary(e){e.preventDefault();if(!requireVip())return;const d=$('#diaryDate').value||dateKey(),x={mood:$('#diaryMood').value,entry:$('#diaryEntry').value.trim(),tomorrow:$('#diaryTomorrow').value.trim(),classDone:$('#diaryClassDone').checked,revisionDone:$('#diaryRevisionDone').checked,targetDone:$('#diaryTargetDone').checked};diaries[d]=x;local.set('diaries',diaries);if(user)await client.from('ypt_diary_entries').upsert({user_id:user.id,entry_date:d,mood:x.mood,entry_text:x.entry,tomorrow_plan:x.tomorrow,class_done:x.classDone,revision_done:x.revisionDone,target_done:x.targetDone},{onConflict:'user_id,entry_date'});loadDiary();toast('Diary saved privately')}
function renderNotes(){const q=($('#vaultSearch').value||'').toLowerCase(),rows=notes.filter(x=>(x.title+' '+x.body+' '+x.subject).toLowerCase().includes(q)).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));$('#vaultNotes').innerHTML=rows.length?rows.map(x=>`<article class="vault-note"><header><span>${esc(x.subject)}</span><button data-delete-note="${x.id}">×</button></header><b>${esc(x.title)}</b><p>${esc(x.body)}</p><small>${new Date(x.created_at).toLocaleString('en-IN')}</small></article>`).join(''):'<div class="empty-real"><b>No notes saved</b>पहला private note बनाएँ।</div>';$$('[data-delete-note]').forEach(b=>b.onclick=async()=>{notes=notes.filter(x=>x.id!==b.dataset.deleteNote);local.set('notes',notes);if(user)await client.from('ypt_private_notes').delete().eq('id',b.dataset.deleteNote).eq('user_id',user.id);renderNotes()})}
async function saveNote(e){e.preventDefault();if(!requireVip())return;const row={id:crypto.randomUUID(),subject:$('#vaultSubject').value,title:$('#vaultTitle').value.trim(),body:$('#vaultBody').value.trim(),created_at:new Date().toISOString()};notes.push(row);local.set('notes',notes);if(user)await client.from('ypt_private_notes').insert({...row,user_id:user.id});e.target.reset();renderNotes();toast('Private note saved')}
async function loadCloudPrivate(){if(!user)return;const [p,d,n]=await Promise.all([client.from('ypt_pw_classes').select('*').eq('user_id',user.id).order('started_at'),client.from('ypt_diary_entries').select('*').eq('user_id',user.id),client.from('ypt_private_notes').select('*').eq('user_id',user.id).order('created_at')]);if(!p.error&&p.data){pwSessions=p.data.map(x=>({id:x.id,date:x.class_date,subject:x.subject,lecture:x.lecture_name,seconds:x.duration_seconds,progress:x.progress_percent,questions:x.questions_attempted,wrong:x.wrong_answers,complete:x.completed,started_at:x.started_at,ended_at:x.ended_at}));local.set('pwSessions',pwSessions)}if(!d.error&&d.data){d.data.forEach(x=>diaries[x.entry_date]={mood:x.mood,entry:x.entry_text,tomorrow:x.tomorrow_plan,classDone:x.class_done,revisionDone:x.revision_done,targetDone:x.target_done});local.set('diaries',diaries)}if(!n.error&&n.data){notes=n.data;local.set('notes',notes)}renderPw();loadDiary();renderNotes()}
async function loadPartner(){if(!user)return;const {data,error}=await client.rpc('get_ypt_partner_state');if(error){$('#partnerStatus').textContent='Run ypt_vip_zone.sql to enable partner sync.';return}const x=data||{};if(x.partner){$('#partnerName').textContent=x.partner.display_name;$('#partnerStatus').textContent='Your active accountability partner';$('#partnerSharedStats').innerHTML=`<div><b>${timeText(x.my_today||0)}</b><small>You today</small></div><div><b>${timeText(x.partner_today||0)}</b><small>Partner today</small></div>`}else{$('#partnerName').textContent='No partner yet';$('#partnerStatus').textContent='Username से request भेजें।';$('#partnerSharedStats').innerHTML=''}$('#partnerRequests').innerHTML=(x.requests||[]).map(r=>`<div class="history-entry"><span>🤝</span><div><b>${esc(r.display_name)}</b><small>Wants to be your focus partner</small></div><div><button data-partner-response="${r.id}" data-accept="1">Accept</button><button data-partner-response="${r.id}" data-accept="0">Reject</button></div></div>`).join('');$$('[data-partner-response]').forEach(b=>b.onclick=async()=>{await client.rpc('respond_ypt_partner',{p_request_id:b.dataset.partnerResponse,p_accept:b.dataset.accept==='1'});loadPartner()})}
async function requestPartner(e){e.preventDefault();if(!requireVip())return;const {data,error}=await client.rpc('request_ypt_partner',{p_username:$('#partnerUsername').value.trim()});toast(error?.message||data?.error||(data?.success?'Request sent':'Could not send'));if(!error)e.target.reset();loadPartner()}
const ROOMS=[['Biology','#35a77b','🧬'],['Physics','#7567e8','⚛️'],['Chemistry','#ff9466','🧪'],['Revision','#e3ad38','📚']];
async function loadStudyverse(){if(!client)return;const cutoff=new Date(Date.now()-120000).toISOString(),{data}=await client.from('ypt_live_sessions').select('*').eq('status','live').gte('last_heartbeat_at',cutoff);const raw=data||[],{data:profiles}=raw.length?await client.from('ypt_profiles').select('id,avatar_url').in('id',raw.map(x=>x.user_id)):{data:[]},avatars=Object.fromEntries((profiles||[]).map(x=>[x.id,avatarReference(x.avatar_url)])),people=raw.map(x=>({...x,avatar_url:avatars[x.user_id]||''}));$('#studyverseLiveCount').textContent=`${people.length} live`;$('#studyverseRooms').innerHTML=ROOMS.map(([name,color,icon])=>{const count=people.filter(x=>x.subject===name).length;return `<article class="studyverse-room" style="--room-color:${color}"><span>${icon}</span><div><b>${name} Room</b><small>${count} studying now</small></div><button data-enter-room="${name}">Enter desk</button></article>`}).join('');$('#studyversePeople').innerHTML=people.length?people.map(x=>`<div>${studyverseAvatar(x)}<b>${esc(x.display_name)}</b><small>${esc(x.subject)} · ${timeText(x.elapsed_seconds)}</small></div>`).join(''):'<div class="empty-real"><b>Campus is quiet</b>Start a focus session to take the first desk.</div>';$$('[data-enter-room]').forEach(b=>b.onclick=()=>{const sel=$('#subjectSelect');if(sel){sel.value=b.dataset.enterRoom;sel.dispatchEvent(new Event('change',{bubbles:true}))}document.querySelector('[data-view="timer"]')?.click()})}
function sendSignal(to,payload){return voice.channel?.send({type:'broadcast',event:'signal',payload:{to,from:user.id,name:userName,...payload}})}
async function peer(remote,offer=false){if(voice.peers.has(remote))return voice.peers.get(remote);const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});voice.peers.set(remote,pc);voice.stream.getTracks().forEach(t=>pc.addTrack(t,voice.stream));pc.onicecandidate=e=>{if(e.candidate)sendSignal(remote,{candidate:e.candidate})};pc.ontrack=e=>{let a=document.querySelector(`audio[data-peer="${remote}"]`);if(!a){a=document.createElement('audio');a.autoplay=true;a.dataset.peer=remote;$('#remoteAudio').appendChild(a)}a.srcObject=e.streams[0]};pc.onconnectionstatechange=()=>{if(['failed','closed','disconnected'].includes(pc.connectionState)){pc.close();voice.peers.delete(remote);document.querySelector(`audio[data-peer="${remote}"]`)?.remove()}};if(offer){const o=await pc.createOffer();await pc.setLocalDescription(o);await sendSignal(remote,{description:pc.localDescription})}return pc}
async function handleSignal(msg){const p=msg.payload;if(!p||p.to!==user?.id)return;let pc=await peer(p.from,false);if(p.description){await pc.setRemoteDescription(p.description);if(p.description.type==='offer'){const a=await pc.createAnswer();await pc.setLocalDescription(a);await sendSignal(p.from,{description:pc.localDescription})}const queued=voice.pending.get(p.from)||[];for(const c of queued)await pc.addIceCandidate(c).catch(()=>{});voice.pending.delete(p.from)}else if(p.candidate){if(pc.remoteDescription)await pc.addIceCandidate(p.candidate).catch(()=>{});else voice.pending.set(p.from,[...(voice.pending.get(p.from)||[]),p.candidate])}}
function renderVoicePresence(){const states=voice.channel?.presenceState()||{},people=Object.values(states).flat();$('#voiceParticipants').innerHTML=people.length?people.map(x=>`<div class="voice-person">${voiceAvatar(x)}<div><b>${esc(x.name||'VIP Member')}</b><small>${x.id===user?.id?'You':'Connected'}</small></div></div>`).join(''):'<div class="empty-real"><b>Waiting for partner</b>Share the same room code.</div>'}
window.addEventListener('rathod-avatar-equipped',event=>{if(event.detail?.avatarUrl)userAvatarUrl=event.detail.avatarUrl;if(voice.channel&&user)voice.channel.track({id:user.id,name:userName,avatar_url:userAvatarUrl,muted:voice.muted,joined_at:new Date().toISOString()});if(document.querySelector('[data-page="studyverse"]')?.classList.contains('active'))loadStudyverse();renderVoicePresence()});
window.addEventListener('rathod-avatar-profile-loaded',event=>{if(event.detail?.avatarUrl)userAvatarUrl=event.detail.avatarUrl});
window.addEventListener('rathod-view-changed',event=>{if(event.detail?.view==='studyverse')loadStudyverse()});
async function joinVoice(){if(!requireVip())return;const room=$('#voiceRoomCode').value.trim().toUpperCase().replace(/[^A-Z0-9-]/g,'');if(!room)return toast('Enter room code');try{if(window.AndroidFocus&&!AndroidFocus.hasAudioPermission()){AndroidFocus.requestAudioPermission();$('#voiceStatus').textContent='Allow microphone permission to join…';for(let i=0;i<40&&!AndroidFocus.hasAudioPermission();i++)await new Promise(r=>setTimeout(r,500));if(!AndroidFocus.hasAudioPermission())return toast('Microphone permission required')}voice.stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true},video:false})}catch{return toast('Microphone permission required')}voice.room=room;voice.channel=client.channel('ypt-voice-'+room,{config:{broadcast:{self:false},presence:{key:user.id}}}).on('broadcast',{event:'signal'},handleSignal).on('presence',{event:'sync'},async()=>{renderVoicePresence();const ids=Object.values(voice.channel.presenceState()).flat().map(x=>x.id).filter(id=>id!==user.id);for(const id of ids)if(user.id<id&&!voice.peers.has(id))await peer(id,true)}).on('presence',{event:'leave'},renderVoicePresence);voice.channel.subscribe(async status=>{if(status==='SUBSCRIBED'){await voice.channel.track({id:user.id,name:userName,avatar_url:userAvatarUrl,muted:false,joined_at:new Date().toISOString()});$('#voiceStatus').textContent=`Connected · ${room}`;$('#voiceJoin').classList.add('hidden');$('#voiceMute').classList.remove('hidden');$('#voiceLeave').classList.remove('hidden')}})}
async function leaveVoice(){for(const pc of voice.peers.values())pc.close();voice.peers.clear();voice.stream?.getTracks().forEach(t=>t.stop());if(voice.channel)await client.removeChannel(voice.channel);voice={channel:null,stream:null,peers:new Map(),pending:new Map(),muted:false,room:''};$('#voiceJoin').classList.remove('hidden');$('#voiceMute').classList.add('hidden');$('#voiceLeave').classList.add('hidden');$('#voiceStatus').textContent='Not connected';$('#voiceParticipants').innerHTML='<div class="empty-real"><b>No room joined</b>Join with a code to begin.</div>';$('#remoteAudio').innerHTML=''}
async function toggleMute(){voice.muted=!voice.muted;voice.stream?.getAudioTracks().forEach(t=>t.enabled=!voice.muted);$('#voiceMute').textContent=voice.muted?'Unmute':'Mute';await voice.channel?.track({id:user.id,name:userName,avatar_url:userAvatarUrl,muted:voice.muted,joined_at:new Date().toISOString()});renderVoicePresence()}
async function init(){if(!window.supabase)return;client=window.supabase.createClient(VIP_SB.url,VIP_SB.key);await session();client.auth.onAuthStateChange(async()=>{await session();loadCloudPrivate();loadPartner()});$('#pwClassForm').onsubmit=handlePw;$('#pwHistoryDate').value=dateKey();$('#pwHistoryDate').onchange=renderPw;$('#diaryDate').value=dateKey();$('#diaryDate').onchange=loadDiary;$('#diaryForm').onsubmit=saveDiary;$('#vaultNoteForm').onsubmit=saveNote;$('#vaultSearch').oninput=renderNotes;$('#partnerRequestForm').onsubmit=requestPartner;$('#voiceJoin').onclick=joinVoice;$('#voiceLeave').onclick=leaveVoice;$('#voiceMute').onclick=toggleMute;window.addEventListener('beforeunload',leaveVoice);renderPw();loadDiary();renderNotes();await loadCloudPrivate();await loadPartner();await loadStudyverse();setInterval(()=>{if(document.querySelector('[data-page="studyverse"]')?.classList.contains('active'))loadStudyverse()},20000)}
init();
