plugins { id 'com.android.application' }

android { namespace 'com.rathod.yptstudy'; compileSdk 35
  compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
  defaultConfig { applicationId 'com.rathod.yptstudy.premium'; minSdk 23; targetSdk 35; versionCode 2; versionName '2.0.0' }
}
